import { CinematicRendererProps } from "./types";

export const signalFromTomorrowWithMusicFixture: CinematicRendererProps = {
  titleFontSize: 78,
  titleWidth: 1320,
  signalLineCount: 18,
  scenes: [
    {
      id: "sc1",
      kind: "title",
      startSeconds: 0,
      durationSeconds: 4,
      text: "SIGNAL FROM TOMORROW",
      accent: "#89d7ff",
      intensity: 1,
    },
    {
      id: "sc2",
      kind: "title",
      startSeconds: 4,
      durationSeconds: 4,
      text: "A LOCAL PREVIEW FIXTURE",
      accent: "#a6e6ff",
      intensity: 0.9,
    },
    {
      id: "sc3",
      kind: "title",
      startSeconds: 8,
      durationSeconds: 3,
      text: "YESTERDAY, THEY LAUNCHED.",
      accent: "#89d7ff",
      intensity: 1,
    },
    {
      id: "sc4",
      kind: "title",
      startSeconds: 11,
      durationSeconds: 7,
      text: "NO EXTERNAL MEDIA REQUIRED",
      accent: "#89d7ff",
      intensity: 1.05,
    },
    {
      id: "sc5",
      kind: "title",
      startSeconds: 18,
      durationSeconds: 3,
      text: "THE SIGNAL CAME FROM EARTH.",
      accent: "#a6e6ff",
      intensity: 1.15,
    },
    {
      id: "sc6",
      kind: "title",
      startSeconds: 21,
      durationSeconds: 6,
      text: "SAFE TO CLICK IN STUDIO",
      accent: "#a6e6ff",
      intensity: 0.95,
    },
    {
      id: "sc7",
      kind: "title",
      startSeconds: 27,
      durationSeconds: 3,
      text: "SIGNAL FROM TOMORROW",
      accent: "#d6f1ff",
      intensity: 0.9,
    },
  ],
};
